#!/bin/bash
#$1 is ras ip 
#$2 is user mac address
#$3 is user ip address with optionally a mask

iptables -D IBSng_FORWARD -m mac --mac-source $2 -s $3 -j ACCEPT
iptables -D IBSng_FORWARD -d $3 -j ACCEPT

#iptables -D IBSng_INPUT -m mac --mac-source $2 -s $3 -j ACCEPT
