from core import defs

ONLINES_SNAPSHOT_COUNT = defs.REALTIME_ONLINES_SNAPSHOT_HOURS*3600 / defs.REALTIME_ONLINES_SNAPSHOT_INTERVAL
USER_BW_SNAPSHOT_COUNT = defs.REALTIME_BW_SNAPSHOT_HOURS*3600 / defs.REALTIME_BW_SNAPSHOT_INTERVAL
